# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore HourGlass/Hourglass.csproj
    - name: Build
      run: dotnet build --no-restore HourGlass/Hourglass.csproj
    - name: Check for build errors
      run: |
        if [ $? -eq 0 ]; then
          echo "Build successful"
        else
          echo "Build failed"
          exit 1
        fi
  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore HourGlass.UnitTests/HourGlass.UnitTests.csproj
    - name: Run tests
      run: dotnet test --no-build --verbosity normal HourGlass.UnitTests/UnitTest1.cs